// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dafqoupboawmnixvzunn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhZnFvdXBib2F3bW5peHZ6dW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjQ3OTcsImV4cCI6MjA2OTA0MDc5N30.-jrFgTGWNEfv5LY2mZkzxtyzUVo67UbTliBZbQk-Br8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});